
export const availableIcons = [
  { value: "Bus", label: "Bus" },
  { value: "Car", label: "Car" },
  { value: "Plane", label: "Plane" },
  { value: "TrainFront", label: "Train" },
  { value: "UtensilsCrossed", label: "Restaurant" },
  { value: "Coffee", label: "Coffee" },
  { value: "Pizza", label: "Pizza" },
  { value: "BedDouble", label: "Bed" },
  { value: "Building2", label: "Hotel" },
  { value: "Home", label: "House" },
  { value: "ShoppingCart", label: "Shopping Cart" },
  { value: "Carrot", label: "Groceries" },
  { value: "ShoppingBag", label: "Shopping" },
  { value: "Tag", label: "Tag" },
  { value: "Gift", label: "Gift" },
  { value: "Activity", label: "Activity" },
  { value: "Map", label: "Map" },
  { value: "Camera", label: "Camera" },
  { value: "Ticket", label: "Ticket" },
  { value: "Beer", label: "Beer" },
  { value: "Wine", label: "Wine" },
  { value: "DollarSign", label: "Dollar" },
  { value: "Euro", label: "Euro" },
  { value: "Receipt", label: "Receipt" },
  { value: "Eye", label: "Eye" },
  { value: "MapPin", label: "Map Pin" },
  { value: "Shirt", label: "Shirt" },
  { value: "Candy", label: "Candy" },
  { value: "Scissors", label: "Scissors" },
  { value: "Smartphone", label: "SIM Card" },
  { value: "IdCard", label: "Passport" },
  { value: "Briefcase", label: "Briefcase" },
  { value: "Dumbbell", label: "Dumbbell" },
  { value: "CreditCard", label: "Credit Card" },
];
